import type { Metadata } from "next"

import { fontMono } from "@/lib/fonts"

import "@/app/styles/globals.css"

export const metadata: Metadata = {
  title: "Next js template",
  description: "This is next js template generated by @rushi-mungse",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={fontMono.className}>{children}</body>
    </html>
  )
}
